export default [
  {
    name: {
      common: "Barbados",
      official: "Barbados",
      nativeName: { eng: { official: "Barbados", common: "Barbados" } },
    },
    tld: [".bb"],
    cca2: "BB",
    ccn3: "052",
    cca3: "BRB",
    cioc: "BAR",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { BBD: { name: "Barbadian dollar", symbol: "$" } },
    idd: { root: "+1", suffixes: ["246"] },
    capital: ["Bridgetown"],
    altSpellings: ["BB"],
    region: "Americas",
    subregion: "Caribbean",
    languages: { eng: "English" },
    translations: {
      ara: { official: "باربادوس", common: "باربادوس" },
      bre: { official: "Barbados", common: "Barbados" },
      ces: { official: "Barbados", common: "Barbados" },
      cym: { official: "Barbados", common: "Barbados" },
      deu: { official: "Barbados", common: "Barbados" },
      est: { official: "Barbados", common: "Barbados" },
      fin: { official: "Barbados", common: "Barbados" },
      fra: { official: "Barbade", common: "Barbade" },
      hrv: { official: "Barbados", common: "Barbados" },
      hun: { official: "Barbados", common: "Barbados" },
      ita: { official: "Barbados", common: "Barbados" },
      jpn: { official: "バルバドス", common: "バルバドス" },
      kor: { official: "바베이도스", common: "바베이도스" },
      nld: { official: "Barbados", common: "Barbados" },
      per: { official: "باربادوس", common: "باربادوس" },
      pol: { official: "Barbados", common: "Barbados" },
      por: { official: "Barbados", common: "Barbados" },
      rus: { official: "Барбадос", common: "Барбадос" },
      slk: { official: "Barbados", common: "Barbados" },
      spa: { official: "Barbados", common: "Barbados" },
      srp: { official: "Барбадос", common: "Барбадос" },
      swe: { official: "Barbados", common: "Barbados" },
      tur: { official: "Barbados", common: "Barbados" },
      urd: { official: "بارباڈوس", common: "بارباڈوس" },
      zho: { official: "巴巴多斯", common: "巴巴多斯" },
    },
    latlng: [13.16666666, -59.53333333],
    landlocked: false,
    area: 430.0,
    demonyms: {
      eng: { f: "Barbadian", m: "Barbadian" },
      fra: { f: "Barbadienne", m: "Barbadien" },
    },
    flag: "\uD83C\uDDE7\uD83C\uDDE7",
    maps: {
      googleMaps: "https://goo.gl/maps/2m36v8STvbGAWd9c7",
      openStreetMaps: "https://www.openstreetmap.org/relation/547511",
    },
    population: 287371,
    fifa: "BRB",
    car: { signs: ["BDS"], side: "left" },
    timezones: ["UTC-04:00"],
    continents: ["North America"],
    flags: {
      png: "https://flagcdn.com/w320/bb.png",
      svg: "https://flagcdn.com/bb.svg",
      alt: "The flag of Barbados is composed of three equal vertical bands of ultramarine, gold and ultramarine. The head of a black trident is centered in the gold band.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/bb.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/bb.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [13.1, -59.62] },
    postalCode: { format: "BB#####", regex: "^(?:BB)*(\\d{5})$" },
  },
  {
    name: {
      common: "Réunion",
      official: "Réunion Island",
      nativeName: {
        fra: { official: "Ile de la Réunion", common: "La Réunion" },
      },
    },
    tld: [".re"],
    cca2: "RE",
    ccn3: "638",
    cca3: "REU",
    independent: false,
    status: "officially-assigned",
    unMember: false,
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    idd: { root: "+2", suffixes: ["62"] },
    capital: ["Saint-Denis"],
    altSpellings: ["RE", "Reunion"],
    region: "Africa",
    subregion: "Eastern Africa",
    languages: { fra: "French" },
    translations: {
      ara: { official: "جزيرة لا ريونيون", common: "لا ريونيون" },
      bre: { official: "Enez ar Reünion", common: "Reünion" },
      ces: { official: "Réunion", common: "Réunion" },
      cym: { official: "Réunion Island", common: "Réunion" },
      deu: { official: "Réunion", common: "Réunion" },
      est: { official: "Réunioni departemang", common: "Réunion" },
      fin: { official: "Réunion", common: "Réunion" },
      fra: { official: "Ile de la Réunion", common: "Réunion" },
      hrv: { official: "Réunion Island", common: "Réunion" },
      hun: { official: "Réunion", common: "Réunion" },
      ita: { official: "Réunion", common: "Riunione" },
      jpn: { official: "レユニオン島", common: "レユニオン" },
      kor: { official: "레위니옹", common: "레위니옹" },
      nld: { official: "Réunion", common: "Réunion" },
      per: { official: "رئونیون", common: "رئونیون" },
      pol: { official: "Reunion", common: "Reunion" },
      por: { official: "Ilha da Reunião", common: "Reunião" },
      rus: { official: "Реюньон", common: "Реюньон" },
      slk: { official: "Réunionský zámorský departmán", common: "Réunion" },
      spa: { official: "Isla de la Reunión", common: "Reunión" },
      srp: { official: "Реинион", common: "Реинион" },
      swe: { official: "Réunion", common: "Réunion" },
      tur: { official: "Réunion", common: "Réunion" },
      urd: { official: "رے یونیوں جزیرہ", common: "رے یونیوں" },
      zho: { official: "留尼旺岛", common: "留尼旺岛" },
    },
    latlng: [-21.15, 55.5],
    landlocked: false,
    area: 2511.0,
    demonyms: {
      eng: { f: "Réunionese", m: "Réunionese" },
      fra: { f: "Réunionnaise", m: "Réunionnais" },
    },
    flag: "\uD83C\uDDF7\uD83C\uDDEA",
    maps: {
      googleMaps: "https://goo.gl/maps/wWpBrXsp8UHVbah29",
      openStreetMaps: "https://www.openstreetmap.org/relation/1785276",
    },
    population: 840974,
    car: { signs: ["F"], side: "right" },
    timezones: ["UTC+04:00"],
    continents: ["Africa"],
    flags: {
      png: "https://flagcdn.com/w320/re.png",
      svg: "https://flagcdn.com/re.svg",
    },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [-20.88, 55.45] },
    postalCode: { format: "#####", regex: "^((97|98)(4|7|8)\\d{2})$" },
  },
  {
    name: {
      common: "Suriname",
      official: "Republic of Suriname",
      nativeName: {
        nld: { official: "Republiek Suriname", common: "Suriname" },
      },
    },
    tld: [".sr"],
    cca2: "SR",
    ccn3: "740",
    cca3: "SUR",
    cioc: "SUR",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { SRD: { name: "Surinamese dollar", symbol: "$" } },
    idd: { root: "+5", suffixes: ["97"] },
    capital: ["Paramaribo"],
    altSpellings: ["SR", "Sarnam", "Sranangron", "Republic of Suriname", "Republiek Suriname"],
    region: "Americas",
    subregion: "South America",
    languages: { nld: "Dutch" },
    translations: {
      ara: { official: "جمهورية سورينام", common: "سورينام" },
      bre: { official: "Republik Surinam", common: "Surinam" },
      ces: { official: "Republika Surinam", common: "Surinam" },
      cym: { official: "Republic of Suriname", common: "Suriname" },
      deu: { official: "Republik Suriname", common: "Suriname" },
      est: { official: "Suriname Vabariik", common: "Suriname" },
      fin: { official: "Surinamen tasavalta", common: "Suriname" },
      fra: { official: "République du Suriname", common: "Surinam" },
      hrv: { official: "Republika Surinam", common: "Surinam" },
      hun: { official: "Suriname Köztársaság", common: "Suriname" },
      ita: { official: "Repubblica del Suriname", common: "Suriname" },
      jpn: { official: "スリナム共和国", common: "スリナム" },
      kor: { official: "수리남 공화국", common: "수리남" },
      nld: { official: "Republiek Suriname", common: "Suriname" },
      per: { official: "جمهوری سورینام", common: "سورینام" },
      pol: { official: "Republika Surinamu", common: "Surinam" },
      por: { official: "República do Suriname", common: "Suriname" },
      rus: { official: "Республика Суринам", common: "Суринам" },
      slk: { official: "Surinamská republika", common: "Surinam" },
      spa: { official: "República de Suriname", common: "Surinam" },
      srp: { official: "Република Суринам", common: "Суринам" },
      swe: { official: "Republiken Surinam", common: "Surinam" },
      tur: { official: "Surinam Cumhuriyeti", common: "Surinam" },
      urd: { official: "جمہوریہ سرینام", common: "سرینام" },
      zho: { official: "苏里南共和国", common: "苏里南" },
    },
    latlng: [4.0, -56.0],
    landlocked: false,
    borders: ["BRA", "GUF", "GUY"],
    area: 163820.0,
    demonyms: {
      eng: { f: "Surinamer", m: "Surinamer" },
      fra: { f: "Surinamaise", m: "Surinamais" },
    },
    flag: "\uD83C\uDDF8\uD83C\uDDF7",
    maps: {
      googleMaps: "https://goo.gl/maps/iy7TuQLSi4qgoBoG7",
      openStreetMaps: "https://www.openstreetmap.org/relation/287082",
    },
    population: 586634,
    gini: { 1999: 57.9 },
    fifa: "SUR",
    car: { signs: ["SME"], side: "left" },
    timezones: ["UTC-03:00"],
    continents: ["South America"],
    flags: {
      png: "https://flagcdn.com/w320/sr.png",
      svg: "https://flagcdn.com/sr.svg",
      alt: "The flag of Suriname is composed of five horizontal bands of green, white, red, white and green in the ratio of 2:1:4:1:2. A large five-pointed yellow star is centered in the red band.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/sr.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/sr.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [5.83, -55.17] },
  },
  {
    name: {
      common: "Namibia",
      official: "Republic of Namibia",
      nativeName: {
        afr: { official: "Republiek van Namibië", common: "Namibië" },
        deu: { official: "Republik Namibia", common: "Namibia" },
        eng: { official: "Republic of Namibia", common: "Namibia" },
        her: { official: "Republic of Namibia", common: "Namibia" },
        hgm: { official: "Republic of Namibia", common: "Namibia" },
        kwn: { official: "Republic of Namibia", common: "Namibia" },
        loz: { official: "Republic of Namibia", common: "Namibia" },
        ndo: { official: "Republic of Namibia", common: "Namibia" },
        tsn: { official: "Lefatshe la Namibia", common: "Namibia" },
      },
    },
    tld: [".na"],
    cca2: "NA",
    ccn3: "516",
    cca3: "NAM",
    cioc: "NAM",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: {
      NAD: { name: "Namibian dollar", symbol: "$" },
      ZAR: { name: "South African rand", symbol: "R" },
    },
    idd: { root: "+2", suffixes: ["64"] },
    capital: ["Windhoek"],
    altSpellings: ["NA", "Namibië", "Republic of Namibia"],
    region: "Africa",
    subregion: "Southern Africa",
    languages: {
      afr: "Afrikaans",
      deu: "German",
      eng: "English",
      her: "Herero",
      hgm: "Khoekhoe",
      kwn: "Kwangali",
      loz: "Lozi",
      ndo: "Ndonga",
      tsn: "Tswana",
    },
    translations: {
      ara: { official: "جمهورية ناميبيا", common: "ناميبيا" },
      bre: { official: "Republik Namibia", common: "Namibia" },
      ces: { official: "Namibijská republika", common: "Namibie" },
      cym: { official: "Republic of Namibia", common: "Namibia" },
      deu: { official: "Republik Namibia", common: "Namibia" },
      est: { official: "Namiibia Vabariik", common: "Namiibia" },
      fin: { official: "Namibian tasavalta", common: "Namibia" },
      fra: { official: "République de Namibie", common: "Namibie" },
      hrv: { official: "Republika Namibija", common: "Namibija" },
      hun: { official: "Namíbiai Köztársaság", common: "Namíbia" },
      ita: { official: "Repubblica di Namibia", common: "Namibia" },
      jpn: { official: "ナミビア共和国", common: "ナミビア" },
      kor: { official: "나미비아 공화국", common: "나미비아" },
      nld: { official: "Republiek Namibië", common: "Namibië" },
      per: { official: "جمهوری نامیبیا", common: "نامیبیا" },
      pol: { official: "Republika Namibii", common: "Namibia" },
      por: { official: "República da Namíbia", common: "Namíbia" },
      rus: { official: "Республика Намибия", common: "Намибия" },
      slk: { official: "Namíbijská republika", common: "Namíbia" },
      spa: { official: "República de Namibia", common: "Namibia" },
      srp: { official: "Република Намибија", common: "Намибија" },
      swe: { official: "Republiken Namibia", common: "Namibia" },
      tur: { official: "Namibya Cumhuriyeti", common: "Namibya" },
      urd: { official: "جمہوریہ نمیبیا", common: "نمیبیا" },
      zho: { official: "纳米比亚共和国", common: "纳米比亚" },
    },
    latlng: [-22.0, 17.0],
    landlocked: false,
    borders: ["AGO", "BWA", "ZAF", "ZMB"],
    area: 825615.0,
    demonyms: {
      eng: { f: "Namibian", m: "Namibian" },
      fra: { f: "Namibienne", m: "Namibien" },
    },
    flag: "\uD83C\uDDF3\uD83C\uDDE6",
    maps: {
      googleMaps: "https://goo.gl/maps/oR1i8BFEYX3EY83WA",
      openStreetMaps: "https://www.openstreetmap.org/relation/195266",
    },
    population: 2540916,
    gini: { 2015: 59.1 },
    fifa: "NAM",
    car: { signs: ["NAM"], side: "left" },
    timezones: ["UTC+01:00"],
    continents: ["Africa"],
    flags: {
      png: "https://flagcdn.com/w320/na.png",
      svg: "https://flagcdn.com/na.svg",
      alt: "The flag of Namibia features a white-edged red diagonal band that extends from the lower hoist-side corner to the upper fly-side corner of the field. Above and beneath this band are a blue and green triangle respectively. A gold sun with twelve triangular rays is situated on the hoist side of the upper triangle.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/na.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/na.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [-22.57, 17.08] },
  },
  {
    name: {
      common: "Guinea",
      official: "Republic of Guinea",
      nativeName: {
        fra: { official: "République de Guinée", common: "Guinée" },
      },
    },
    tld: [".gn"],
    cca2: "GN",
    ccn3: "324",
    cca3: "GIN",
    cioc: "GUI",
    independent: true,
    status: "officially-assigned",
    unMember: true,
    currencies: { GNF: { name: "Guinean franc", symbol: "Fr" } },
    idd: { root: "+2", suffixes: ["24"] },
    capital: ["Conakry"],
    altSpellings: ["GN", "Republic of Guinea", "République de Guinée"],
    region: "Africa",
    subregion: "Western Africa",
    languages: { fra: "French" },
    translations: {
      ara: { official: "جمهورية غينيا", common: "غينيا" },
      bre: { official: "Republik Ginea", common: "Ginea" },
      ces: { official: "Guinejská republika", common: "Guinea" },
      cym: { official: "Republic of Guinea", common: "Guinea" },
      deu: { official: "Republik Guinea", common: "Guinea" },
      est: { official: "Guinea Vabariik", common: "Guinea" },
      fin: { official: "Guinean tasavalta", common: "Guinea" },
      fra: { official: "République de Guinée", common: "Guinée" },
      hrv: { official: "Republika Gvineja", common: "Gvineja" },
      hun: { official: "Guineai Köztársaság", common: "Guinea" },
      ita: { official: "Repubblica di Guinea", common: "Guinea" },
      jpn: { official: "ギニア共和国", common: "ギニア" },
      kor: { official: "기니 공화국", common: "기니" },
      nld: { official: "Republiek Guinee", common: "Guinee" },
      per: { official: "مملکت مستقل پاپوآ گینه نو", common: "پاپوآ گینه نو" },
      pol: { official: "Republika Gwinei", common: "Gwinea" },
      por: { official: "República da Guiné", common: "Guiné" },
      rus: { official: "Республика Гвинея", common: "Гвинея" },
      slk: { official: "Guinejská republika", common: "Guinea" },
      spa: { official: "República de Guinea", common: "Guinea" },
      srp: { official: "Кооперативна Република Гвајана", common: "Гвајана" },
      swe: { official: "Republiken Guinea", common: "Guinea" },
      tur: { official: "Gine Cumhuriyeti", common: "Gine" },
      urd: { official: "جمہوریہ گنی", common: "گنی" },
      zho: { official: "几内亚共和国", common: "几内亚" },
    },
    latlng: [11.0, -10.0],
    landlocked: false,
    borders: ["CIV", "GNB", "LBR", "MLI", "SEN", "SLE"],
    area: 245857.0,
    demonyms: {
      eng: { f: "Guinean", m: "Guinean" },
      fra: { f: "Guinéenne", m: "Guinéen" },
    },
    flag: "\uD83C\uDDEC\uD83C\uDDF3",
    maps: {
      googleMaps: "https://goo.gl/maps/8J5oM5sA4Ayr1ZYGA",
      openStreetMaps: "https://www.openstreetmap.org/relation/192778",
    },
    population: 13132792,
    gini: { 2012: 33.7 },
    fifa: "GUI",
    car: { signs: ["RG"], side: "right" },
    timezones: ["UTC"],
    continents: ["Africa"],
    flags: {
      png: "https://flagcdn.com/w320/gn.png",
      svg: "https://flagcdn.com/gn.svg",
      alt: "The flag of Guinea is composed of three equal vertical bands of red, yellow and green.",
    },
    coatOfArms: {
      png: "https://mainfacts.com/media/images/coats_of_arms/gn.png",
      svg: "https://mainfacts.com/media/images/coats_of_arms/gn.svg",
    },
    startOfWeek: "monday",
    capitalInfo: { latlng: [9.5, -13.7] },
  },
];
